// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5mp9KriFLnpq8-eahrqFUNvmbBq4vRKU',
    appId: '1:770385124301:web:d8eb0fdf493664a84d0284',
    messagingSenderId: '770385124301',
    projectId: 'chat-app-5d891',
    authDomain: 'chat-app-5d891.firebaseapp.com',
    storageBucket: 'chat-app-5d891.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJeHpnE0XWDlfSzDMIO3wW7mN4AMUG5Ps',
    appId: '1:770385124301:android:4493053f34b537e34d0284',
    messagingSenderId: '770385124301',
    projectId: 'chat-app-5d891',
    storageBucket: 'chat-app-5d891.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTIOKaAd-LsTb6hMQ5pqEGlKSmtyKIoO4',
    appId: '1:770385124301:ios:e195843b470777f34d0284',
    messagingSenderId: '770385124301',
    projectId: 'chat-app-5d891',
    storageBucket: 'chat-app-5d891.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTIOKaAd-LsTb6hMQ5pqEGlKSmtyKIoO4',
    appId: '1:770385124301:ios:28c5887d48bb03344d0284',
    messagingSenderId: '770385124301',
    projectId: 'chat-app-5d891',
    storageBucket: 'chat-app-5d891.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
